kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  namespace: mw
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mw
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      containers:
        - name: postgres
          image: postgres:14.1
          env:
            - name: POSTGRES_PASSWORD
              value: "admin123"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
#            - name: mysql-conf
#              mountPath: /etc/mysql/conf.d
#              readOnly: true
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      nodeSelector:
        master: "true"
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mw
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30004
  selector:
    app: postgres
