apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-single
  namespace: mw
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-single
          image: bitnami/kafka:3.1.0
          env:
            - name: "KAFKA_CFG_BROKER_ID"
              value: "1"
            - name: "KAFKA_CFG_LISTENERS"
              value: "PLAINTEXT://0.0.0.0:9092"
            - name: "KAFKA_CFG_ADVERTISED_LISTENERS"
              value: "PLAINTEXT://kafka-single.mw.svc.cluster.local:30008"
            - name: "KAFKA_CFG_ZOOKEEPER_CONNECT"
              value: "zookeeper-single:2181"
            - name: "ALLOW_PLAINTEXT_LISTENER"
              value: "yes"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: kafka-single-data
              mountPath: /bitnami/kafka/data
            - name: kafka-single-logs
              mountPath: /bitnami/kafka/logs
      nodeSelector:
        master: "true"
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: kafka-single-data
          persistentVolumeClaim:
            claimName: kafka-single-data
        - name: kafka-single-logs
          persistentVolumeClaim:
            claimName: kafka-single-logs

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-single
  namespace: mw
spec:
  type: NodePort
  ports:
    - port: 30008
      targetPort: 9092
      nodePort: 30008
  selector:
    app: kafka
