kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/wizard/k8s-volume/mysql/volume-mysql

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: mysql

