kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-data
  namespace: mobe-cloud
  labels:
    app: mysql-data
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/k8s-volume/mysql/data

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data
  namespace: mobe-cloud
  labels:
    app: mysql-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      app: mysql-data

