kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data
  namespace: mobe-cloud
  labels:
    app: redis-data
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/k8s-volume/redis/data

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
  namespace: mobe-cloud
  labels:
    app: redis-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: redis-data

