kind: PersistentVolume
apiVersion: v1
metadata:
  name: timezone
  namespace: mobe-cloud
  labels:
    app: timezone
spec:
  storageClassName: manual
  capacity:
    storage: 3Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/k8s-volume/common/timezone

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: timezone
  namespace: mobe-cloud
  labels:
    app: timezone
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi
  selector:
    matchLabels:
      app: timezone

