apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 22306
      targetPort: 3306
      protocol: TCP
      nodePort: 32306
  selector:
    app: mysql