apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mobe-cloud
spec:
  type: NodePort
  ports:
    - port: 20002
      targetPort: 3306
      protocol: TCP
      nodePort: 30002
  selector:
    app: mysql
