apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mobe-cloud
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin123"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              subPath: localtime
              readOnly: true
            - mountPath: /var/lib/mysql
              name: mysql-data
            - mountPath: /etc/mysql
              name: mysql-conf

      volumes:
        - name: timezone
          persistentVolumeClaim:
            claimName: timezone
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
        - name: mysql-conf
          hostPath:
            path: /data/k8s-volume/mysql/conf
