apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mobe-cloud
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          args: ["--appendonly", "yes"]
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              subPath: localtime
              readOnly: true
            - mountPath: /data
              name: redis-data
            - mountPath: /usr/local/etc/redis/redis.conf
              name: redis-conf
              subPath: redis.conf
              readOnly: true

      volumes:
        - name: timezone
          persistentVolumeClaim:
            claimName: timezone
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
        - name: redis-conf
          hostPath:
            path: /data/k8s-volume/redis/conf
