apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-ui
  namespace: mw
spec:
  selector:
    matchLabels:
      app: debezium-ui
  template:
    metadata:
      labels:
        app: debezium-ui
    spec:
      containers:
        - name: debezium-ui
          image: debezium/debezium-ui:1.9
          env:
            - name: "KAFKA_CONNECT_URIS"
              value: "http://debezium-connect:8083"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
      nodeSelector:
        master: "true"
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---
apiVersion: v1
kind: Service
metadata:
  name: debezium-ui
  namespace: mw
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30018
  selector:
    app: debezium-ui


